import type { Metadata } from 'next'
import './globals.css'
import Nav from '@/components/Nav'
import { AuthProvider } from '@/components/AuthProvider'
import LoginState from '@/components/LoginState'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  readonly children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <Nav>
          <LoginState />
        </Nav>
        <AuthProvider>
          { children }
        </AuthProvider>
      </body>
    </html>
  )
}
